// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'key',
    appId: '1:539934290897:web:043b05cdf63a2ea5c5e6f0',
    messagingSenderId: '539934290897',
    projectId: 'cadastro-cliente-40ac6',
    authDomain: 'cadastro-cliente-40ac6.firebaseapp.com',
    storageBucket: 'cadastro-cliente-40ac6.firebasestorage.app',
    measurementId: 'G-WN7PC8B77R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'key',
    appId: '1:539934290897:android:7f47999ab93469f2c5e6f0',
    messagingSenderId: '539934290897',
    projectId: 'cadastro-cliente-40ac6',
    storageBucket: 'cadastro-cliente-40ac6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'key',
    appId: '1:539934290897:ios:fe1f9fedc70a02f1c5e6f0',
    messagingSenderId: '539934290897',
    projectId: 'cadastro-cliente-40ac6',
    storageBucket: 'cadastro-cliente-40ac6.firebasestorage.app',
    iosBundleId: 'com.example.cadastroCliente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'key',
    appId: '1:539934290897:ios:fe1f9fedc70a02f1c5e6f0',
    messagingSenderId: '539934290897',
    projectId: 'cadastro-cliente-40ac6',
    storageBucket: 'cadastro-cliente-40ac6.firebasestorage.app',
    iosBundleId: 'com.example.cadastroCliente',
  );
}
